CREATE TABLE Sale (
    id BIGINT AUTO_INCREMENT PRIMARY KEY
    CUSTOMER_ID BIGINT NOT NULL,
    GROSS_VALUE NUMERIC NOT NULL,
    NET_VALUE NUMERIC NOT NULL,
    DISCOUNT_VALUE NUMERIC NOT NULL,
    CREATED_AT DATE NOT NULL
);


CREATE TABLE SaleNote (
    id BIGINT AUTO_INCREMENT PRIMARY KEY
    SALE_ID BIGINT NOT NULL,
    NUMBER BIGINT NOT NULL,
    FILE_ID VARCHAR(100) NOT NULL,
    FOLDER VARCHAR(300) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CONSTRAINT FK_SALE_NOTE_SALE FOREIGN KEY (SALE_ID) REFERENCES Sale (id)
);
